-- MySQL Script generated by MySQL Workbench
-- Fri Jun 12 21:22:25 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`usertypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`usertypes` (
  `id` BIGINT(11) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`users` (
  `id` BIGINT(11) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL,
  `type` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `USER_TYPE_idx` (`type` ASC),
  CONSTRAINT `USER_TYPE`
    FOREIGN KEY (`type`)
    REFERENCES `ecommerce`.`usertypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`products` (
  `id` BIGINT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `quantity` INT NOT NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`cartstatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`cartstatus` (
  `id` BIGINT(11) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`carts` (
  `id` BIGINT(11) NOT NULL,
  `owner` BIGINT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `status` BIGINT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CART_STATUS_idx` (`status` ASC),
  INDEX `CART_OWNER_idx` (`owner` ASC),
  CONSTRAINT `CART_OWNER`
    FOREIGN KEY (`owner`)
    REFERENCES `ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CART_STATUS`
    FOREIGN KEY (`status`)
    REFERENCES `ecommerce`.`cartstatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecommerce`.`cartproducts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`cartproducts` (
  `cartid` BIGINT(11) NOT NULL,
  `productid` BIGINT(11) NOT NULL,
  PRIMARY KEY (`cartid`, `productid`),
  INDEX `PRODUCT_ID_idx` (`productid` ASC),
  CONSTRAINT `CART_ID`
    FOREIGN KEY (`cartid`)
    REFERENCES `ecommerce`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PRODUCT_ID`
    FOREIGN KEY (`productid`)
    REFERENCES `ecommerce`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Default Admin User
INSERT INTO users (username, password, type) VALUES ('admin@mail.com’, '$2a$10$d8yU515yNMaZxHJVJM1tpOW8Sz2xqe0h3ZKmkWH7/PsnHtJFeWf/W', 1);
